# Numpy-01

- <https://jakevdp.github.io/PythonDataScienceHandbook/02.01-understanding-data-types.html>

In [4]:
import numpy as np

In [2]:
np.__version__

'2.3.5'

## Creating Arrays from Python Lists

In [3]:
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

In [4]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

In [5]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

In [6]:
# nested lists in multi-dimensional arrays
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

## Creating Arrays from Scratch

In [7]:
# create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

In [9]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

---

In [8]:
a = np.array([range(i, i+3) for i in [2, 4, 6]])
print(a)
np.zeros_like(a)

[[2 3 4]
 [4 5 6]
 [6 7 8]]


array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [10]:
# create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [11]:
# create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [12]:
# create an array filled with a linear sequence
# starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [13]:
# create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [14]:
# create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.91398101, 0.60851471, 0.84069546],
       [0.39912434, 0.99133577, 0.29780291],
       [0.17410044, 0.19135448, 0.33863098]])

In [15]:
# create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[ 0.45253723, -0.1168666 , -0.60900215],
       [-0.1536995 , -0.64185174, -2.73276241],
       [-0.19201068, -1.17424493,  1.25150862]])

In [16]:
# create a 3x3 array of random integers in the interval [0,10)
np.random.randint(0, 10, (3,3))

array([[2, 3, 9],
       [5, 5, 8],
       [0, 0, 1]])

In [17]:
# create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
# create an uninitialized array of three integers
# the values will be whatever happens to already exist at that momory location
np.empty(3)

array([1., 1., 1.])