# Numpy-02

- <https://jakevdp.github.io/PythonDataScienceHandbook/02.02-the-basics-of-numpy-arrays.html>

## Numpy Array Attributes

In [1]:
import numpy as np

# seed for reproducibility
np.random.seed(0) 

# one-dimensional array
x1 = np.random.randint(10, size=6)
# two-dimensional array
x2 = np.random.randint(10, size=(3, 4))
# three-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))

print("x3.ndim:\t", x3.ndim)
print("x3.shape:\t", x3.shape)
print("x3.size:\t", x3.size)
print("x3.dtype:\t", x3.dtype)
print("x3.itemsize:\t", x3.itemsize, "bytes")
print("x3.nbytes:\t", x3.nbytes, "bytes")

x3.ndim:	 3
x3.shape:	 (3, 4, 5)
x3.size:	 60
x3.dtype:	 int64
x3.itemsize:	 8 bytes
x3.nbytes:	 480 bytes


## Array Indexing: Accessing Single Elements

In [2]:
x1

array([5, 0, 3, 3, 7, 9])

In [3]:
x1[0]

np.int64(5)

In [4]:
x1[4]

np.int64(7)

In [5]:
x1[-1]

np.int64(9)

In [6]:
x1[-2]

np.int64(7)

---

In [7]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [8]:
x2[0, 0]

np.int64(3)

In [9]:
x2[2, 0]

np.int64(1)

In [10]:
x2[2, -1]

np.int64(7)

---

In [11]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [12]:
x1[0] = 3.14158 # this will be truncated
x1

array([3, 0, 3, 3, 7, 9])

## Array Slicing: Accessing Subarrays

### One-dimensional subarrays

In [13]:
x= np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [14]:
# first five elements
x[:5]

array([0, 1, 2, 3, 4])

In [15]:
# elements after index 5
x[5:]

array([5, 6, 7, 8, 9])

In [16]:
# middle sub-array
x[4:7]

array([4, 5, 6])

In [17]:
# every other element
x[::2]

array([0, 2, 4, 6, 8])

In [18]:
# every other element, starting at index 1
x[1::2]

array([1, 3, 5, 7, 9])

In [19]:
# all elements, reversed
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [20]:
# reserved every other from index 5
x[5::-2]

array([5, 3, 1])

### Multi-dimensional subarrays

In [21]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [22]:
# two rows, three columns
x2[:2, :3]

array([[12,  5,  2],
       [ 7,  6,  8]])

In [23]:
# all rows, every other column
x2[:3, ::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [24]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Accessing array rows and columns

In [25]:
# first column of x2
print(x2[:, 0])

[12  7  1]


In [26]:
# first row of x2
print(x2[0, :])

[12  5  2  4]


In [27]:
# equivalent to x2[0, :]
print(x2[0])

[12  5  2  4]


### Subarrays as no-copy views

In [28]:
print(x2)

[[12  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


In [29]:
x2_sub = x2[:2, :2]
print(x2_sub)

[[12  5]
 [ 7  6]]


In [30]:
x2_sub[0, 0] = 99
print(x2_sub)

[[99  5]
 [ 7  6]]


In [31]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


### Creating copies of arrays

In [32]:
x2_sub_copy = x2[:2, :2].copy()
print(x2_sub_copy)

[[99  5]
 [ 7  6]]


In [33]:
x2_sub_copy[0, 0] = 42
print(x2_sub_copy)

[[42  5]
 [ 7  6]]


In [34]:
print(x2)

[[99  5  2  4]
 [ 7  6  8  8]
 [ 1  6  7  7]]


## Reshaping of Arrays

In [35]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
x = np.array([1, 2, 3])

# row vector via reshape
x.reshape((1, 3))

array([[1, 2, 3]])

In [37]:
# row vector via newaxis
x[np.newaxis, :]

array([[1, 2, 3]])

In [38]:
# column vector via reshape
x.reshape((3, 1))

array([[1],
       [2],
       [3]])

In [39]:
# column vector via newaxis
x[:, np.newaxis]

array([[1],
       [2],
       [3]])

## Array Concatenation and Splitting

### Concatenation of Arrays

In [40]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

In [41]:
z = [99, 99, 99]
print(np.concatenate([x, y, z]))

[ 1  2  3  3  2  1 99 99 99]


In [42]:
grid = np.array([[1, 2, 3],
                 [4, 5, 6]])

In [43]:
# concatenate along the first axis
np.concatenate([grid, grid])

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [44]:
# concatenate along the second axis (zero-indexed)
np.concatenate([grid, grid], axis=1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

---

In [45]:
x = np.array([1, 2, 3])
grid = np.array([[9, 8, 7],
                 [6, 5, 4]])

# vertically stack the array
np.vstack([x, grid])

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

In [46]:
# horizontally stack the arrays
y = np.array([[99],
              [99]])
np.hstack([grid, y])

array([[ 9,  8,  7, 99],
       [ 6,  5,  4, 99]])

### Splitting of arrays

In [47]:
x = [1, 2, 3, 99, 99, 3, 2, 1]
x1, x2, x3 = np.split(x, [3, 5])
print(x1, x2, x3)

[1 2 3] [99 99] [3 2 1]


In [48]:
grid = np.arange(16).reshape((4, 4))
grid

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [49]:
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


In [50]:
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]]
[[ 2  3]
 [ 6  7]
 [10 11]
 [14 15]]
